### ISSUE TITLE
softlocks: healing rain?

### ISSUE THREAD

**Issue by pancelor** [joeribakker/cantrip#10]
Here are all the softlocks I've hit so far; the game log seemed like it might be useful so I took screenshots, but I was never too aware of what exactly was happening to cause the softlock. In general, these tended to happen during big complicated turns... I want to say maybe there are issues with multi-turn effects like Healing Rain running out if you play another Healing Rain before the first one runs out? It's hard to say, and quite possibly of course these softlocks are the result of multiple different bugs, etc etc.

One other vague thing that might be relevant: I've stopped taking Healing Rain and Life Link as often as I used to, and it seems like I've had fewer softlocks. (possibly this is unrelated, quite probably there are other cards i take more/less often now that might be the culprits instead, maybe this is all confirmation bias, but hey, maybe those cards would be a good first place to look)

softlock 1: yaga, wellspring
![2020_11_23_03_54_28_072_cantrip softlock 1](https://user-images.githubusercontent.com/11308928/100213999-913f8f80-2ecc-11eb-9d0c-e92669d2c4d2.png)
(I already reported this one in the itch.io comments)

softlock 2: spear knight, healing rain
![2020_11_23_14_43_58_102_cantrip softlock 2](https://user-images.githubusercontent.com/11308928/100214141-bc29e380-2ecc-11eb-899d-76533b445f12.png)
check out that log, something's definitely up with healing rain

softlock 3: mind flayer, healing rain. [video!](https://www.twitch.tv/videos/815122096)
some notes about this one:
* in the clip I say "it played siphon but i didn't have any AP" but actually this was wrong, I had 1 AP from playing rest the previous turn
* the very last line of the log is a bit confusing b/c it sounds like the mindflayer used healing rain, but actually I think that's just a (separate?) bug with the log -- sometimes it attributes stuff like that to the wrong player
* the log definitely makes healing rain look suspicious here

softlock 4: mind flayer, possess, barter for power
![2020_11_24_03_29_33_433_cantrip softlock 4](https://user-images.githubusercontent.com/11308928/100214835-92bd8780-2ecd-11eb-82e1-760d940b5069.png)
This was after a long, confusing mindflayer fight

softlock 5: kobold, healing rain
![2020_11_24_15_21_16_535_cantrip softlock 5](https://user-images.githubusercontent.com/11308928/100215161-ec25b680-2ecd-11eb-9b13-d57a713b6f4b.png)
I was getting absolutely trashed by a 1-1 kobold who stole my healing rain; lots of stuff happened and suddenly he stopped doing stuff in the middle of his turn and softlocked

Hopefully this is useful! After looking through these screenshots right now, I'm very suspicious of healing rain, and mildy suspicious of the mind flayer

**Comment by bakkerjoeri** [comment]
Thanks for the very detailed report! You're definitely on to something: Someone else reported another soft lock, and what do you know, healing rain was in the mix, and so was life link https://itch.io/post/2232372.

When I have some time, I'm gonna set up a debug deck with a bunch of "Healing rain" and card draw cards and see if I can reproduce the soft lock, figure out what states they're freezing in, and have a good look at the code.

I'll will let you know what I find.

**Comment by pancelor** [comment]
I caught some more on [video](https://www.youtube.com/watch?v=QjoBYO7FN7U)! Something's definitely up with healing rain. #1 seems pretty typical to my experience, #2 seems extremely similar to #1 but _doesn't_ manifest the bug, and #3 seems especially useful, since it's such a short reproduction (I only played healing rain twice)

**Comment by bakkerjoeri** [comment]
Oh, sweet! Thanks so much. Every detail and case helps heaps. Your first report already helped narrow things down a lot, so I'm eager to look at these as well.

Some good news: I've managed to consistently trigger one type of soft lock! One of the cases in which it seems to happen is when there are a few turn-opening card draw effects, and the character drawing needs to reshuffle also. They're forced into `drawingCards` state while in `reshufflingCards`, then revert to the shuffling state one rather than `waiting` and get stuck.

Here's a screenshot of the game in debug mode at that state:

![image](https://user-images.githubusercontent.com/1791066/100323292-caa7f600-2fc5-11eb-94fb-9dbedd8e9432.png)

So that's at least one cause, and I have an idea of how it could be fixed, but there must be more to the soft locks, because I think this case doesn't explain what happened in your recording with the Mind Flayer, where it froze after ending clicking "end turn" but before actually progressing to the opponent's turn, signified by the grayed out "end turn" button, as you called out correctly.

The mystery continues. for now!

**Comment by bakkerjoeri** [comment]
Ah neat, that reshuffle interruption theory also tracks with the soft locks in your latest video. And look at what I saw in your video too. It's in almost all the screenshots too, but I missed it until now:

![image](https://user-images.githubusercontent.com/1791066/100330546-625e1200-2fcf-11eb-870b-2a38f68245b1.png)

The pile sizes are wrong, which would further reinforce that theory: reshuffling immediately moves everything from one list to another, but switches card states from `inGraveyard` to `inDrawPile` at a delay to animate that action. If it's interrupted, some cards are left out of that animation and stay in the graveyard visually.

**Comment by bakkerjoeri** [comment]
@pancelor I was studying your Twitch clip of the battle against the Mind Flayer again, and realized that it too can be explained by the reshuffle interruption theory, but it takes a while to finally to take hold. This is what happens:

1. The Mind Flayer has "Life link" active, an empty draw pile, and you have "Healing rain" active.
2. Your turn starts, you draw.
3. Life link activates for that draw, Mind Flayer starts reshuffling so it can draw that card.
4. A few frames later, "Healing rain" activates, and you draw again while the Mind Flayer is reshuffling.
5. The Mind Flayer is forced out of reshuffling to draw another, and falls into a weird intermediate state.
6. The rest of your turn happens, and at the end you rest and your turn ends.
7. The Mind Flayer is still in `reshufflingCards` state and this causes a soft lock.

The way the `reshufflingCards` is set up is just too susceptible to interruptions. I'm working out a solution at the moment. This is great, by the way, because that means the reported cases all share a single cause and I can deal with it all at once. Your stream was up until now the only odd one out.

**Comment by bakkerjoeri** [comment]
Probably it's fully solved by #11. Will close until reported again. Thanks again for all the reports @pancelor.

**Comment by bakkerjoeri** [comment]
The fix is live in [v3.1.1](https://bakkerjoeri.itch.io/cantrip/devlog/200113/cantrip-311)!
